[package]
name = "aexClock"
version = "0.4.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
chrono = "0.4"
unicode-width = "0.1"
once_cell = "1.17"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"

